const social = [
  {
    id: 1,
    name: "Custom URL",
    platform: "Custom",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/custom.png",
  },
  {
    id: 2,
    name: "Reddit",
    platform: "Reddit",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/reddit.png",
  },
  {
    id: 3,
    name: "Instagram",
    platform: "Instagram",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/instagram.png",
  },
  {
    id: 4,
    name: "Twitter",
    platform: "Twitter",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/twitter.png",
  },
  {
    id: 5,
    name: "TikTok",
    platform: "TikTok",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/tiktok.png",
  },
  {
    id: 6,
    name: "Twitch",
    platform: "Twitch",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/twitch.png",
  },
  {
    id: 7,
    name: "Facebook",
    platform: "Facebook",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/facebook.png",
  },
  {
    id: 8,
    name: "YouTube",
    platform: "YouTube",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/youtube.png",
  },
  {
    id: 9,
    name: "Tumblr",
    platform: "Tumblr",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/tumblr.png",
  },
  {
    id: 10,
    name: "Spotify",
    platform: "Spotify",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/spotify.png",
  },
  {
    id: 11,
    name: "SoundCloud",
    platform: "SoundCloud",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/soundcloud.png",
  },
  {
    id: 12,
    name: "Beacons",
    platform: "Beacons",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/beacons.png",
  },
  {
    id: 13,
    name: "Linktree",
    platform: "Linktree",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/linktree.png",
  },
  {
    id: 14,
    name: "Discord",
    platform: "Discord",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/discord.png",
  },
  {
    id: 15,
    name: "Venmo",
    platform: "Venmo",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/venmo.png",
  },
  {
    id: 16,
    name: "Cash App",
    platform: "Cash App",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/cash_app.png",
  },
  {
    id: 17,
    name: "Patreon",
    platform: "Patreon",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/patreon.png",
  },
  {
    id: 18,
    name: "Kofi",
    platform: "Kofi",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/kofi.png",
  },
  {
    id: 19,
    name: "PayPal",
    platform: "PayPal",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/paypal.png",
  },
  {
    id: 20,
    name: "Cameo",
    platform: "Cameo",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/cameo.png",
  },
  {
    id: 21,
    name: "OnlyFans",
    platform: "OnlyFans",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/onlyfans.png",
  },
  {
    id: 22,
    name: "Substack",
    platform: "Substack",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/substack.png",
  },
  {
    id: 23,
    name: "Kickstarter",
    platform: "Kickstarter",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/kickstarter.png",
  },
  {
    id: 24,
    name: "Buy Me a Coffee",
    platform: "Buy Me a Coffee",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/buy_me_a_coffee.png",
  },
  {
    id: 25,
    name: "Shopify",
    platform: "Shopify",
    logo: "https://www.redditstatic.com/desktop2x/img/social-links/shopify.png",
  },
  {
    id: 26,
    name: "Spreadit",
    platform: "Spreadit",
    logo: "../assets/logoSpreadIt.svg",
  },
];

export default social;
